module.exports = [
    'amazon',
    'flipkart',
    'ajio',
    'cleartrip',
    'clovia',
    'croma',
    'lenskart',
    'limeroad',
    'myntra',
    'nykaa',
    'oneplus',
    'pepperfry',
    'snapDeal',
    'tatacliq',
    'zivame',
    'healthkart',
    'shopclues',
    'the man company',
    'udemy',
    'mamaearth',
    'beardo',
    'wow',
    'boat',
    'zandu care',
    'ustraa',
    'durex',
    'medibuddy',
    'mcaffeine',
    'kapiva',
    'just Herbs',
    'body cupid',
    'bombay shaving company',
    'xyxx'
]
